name: CondaCI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  windows-tests:
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        python_version: [3.7, 3.8, 3.9]
        conda_subdir: ['win-64']
        test_type: ['unit', 'integration']
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Link conda and source folders on temp drive
      shell: cmd
      run: |
        @ECHO ON
        pushd %TEMP%
        set CONDA=C:\Miniconda
        mklink /J \conda_bin %CONDA%
        mklink /J \conda_src %GITHUB_WORKSPACE%

    - name: Initialize test environment
      shell: cmd
      run: |
        @ECHO ON
        set CONDA_SUBDIR=${{ matrix.conda_subdir }}
        if ${{ matrix.python_version }} == 2.7 set SCANDIR=scandir
        pushd %TEMP%
        cd \conda_src
        CALL \conda_bin\scripts\activate.bat
        CALL conda create -n ci_base -y python=${{ matrix.python_version }} pycosat conda requests ruamel_yaml pytest pytest-cov pytest-timeout mock responses urllib3 pexpect pywin32 anaconda-client conda-package-handling %SCANDIR%
        CALL conda activate ci_base
        CALL conda install -yq pip conda-build conda-verify
        CALL conda update openssl ca-certificates certifi
        pip install codecov
        python -m conda init cmd.exe --dev
      
    - name: Build activate-deactivate package
      shell: cmd
      run: |
        @ECHO ON
        pushd %TEMP%
        cd \conda_src
        CALL dev-init.bat
        CALL conda info -a
        CALL conda-build tests\test-recipes\activate_deactivate_package
    
    - name: py${{ matrix.python_version }} ${{ matrix.conda_subdir }} unit tests
      shell: cmd
      if: ${{ matrix.test_type == 'unit' }}
      run: |
        @ECHO ON
        pushd %TEMP%
        cd \conda_src
        CALL dev-init.bat
        CALL py.test -m "not integration and not installed" --junitxml=junit/test-results-unit.xml --cov=conda --cov-report=xml -v
    
    - name: py${{ matrix.python_version }} ${{ matrix.conda_subdir }} integration test group 1
      shell: cmd
      if: ${{ matrix.test_type == 'integration' }}
      run: |
        @ECHO ON
        pushd %TEMP%
        cd \conda_src
        CALL dev-init.bat
        CALL py.test -m "integration and not installed" -k "cli" --basetemp=C:\tmp --junitxml=junit/test-results-integration_g1.xml --cov=conda --cov-report=xml -v

    - name: py${{ matrix.python_version }} ${{ matrix.conda_subdir }} integration test group 2
      shell: cmd
      if: ${{ matrix.test_type == 'integration' }}
      run: |
        @ECHO ON
        pushd %TEMP%
        cd \conda_src
        CALL dev-init.bat
        CALL py.test -m "integration and not installed" -k "not cli" --basetemp=C:\tmp  --junitxml=junit/test-results-integration_g2.xml --cov=conda --cov-report=xml -v --cov-append

    - name: 'Upload to codecov.io'
      shell: cmd
      run: |
        pushd %TEMP%
        cd \conda_src
        curl -s https://codecov.io/bash > codecov_uploader.sh
        bash -c ". codecov_uploader.sh -C $GITHUB_SHA"

  build_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: build the docs
        uses: docker://continuumio/conda-ci-linux-64-python3.7:latest
        with:
          entrypoint: /bin/bash
          args: ./ci/build_docs.sh
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: flake8
        uses: docker://continuumio/conda-ci-linux-64-python3.7:latest
        with:
          entrypoint: /bin/bash
          args: -c "/opt/conda/bin/flake8 --statistics"

  linux-tests-py37:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test_type: ['unit', 'integration']
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: py37 unit tests
        if: ${{ matrix.test_type == 'unit' }}
        uses: docker://continuumio/conda-ci-linux-64-python3.7:latest
        with:
          entrypoint: /bin/bash
          args: ./ci/unit_test.sh
      - name: py37 integration tests
        if: ${{ matrix.test_type == 'integration' }}
        uses: docker://continuumio/conda-ci-linux-64-python3.7:latest
        with:
          entrypoint: /bin/bash
          args: ./ci/integration_tests.sh
      - name: upload codecov
        run: |
          if [[ $(git diff origin/master --name-only | wc -l) == $(git diff origin/master --name-only | grep docs | wc -l) && $(git diff origin/master --name-only | grep docs) ]]; then
            echo "No codecov report to upload"
          else
            bash <(curl -s https://codecov.io/bash)
          fi

  linux-tests-py38:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test_type: ['unit', 'integration']
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: py38 unit tests
        if: ${{ matrix.test_type == 'unit' }}
        uses: docker://continuumio/conda-ci-linux-64-python3.8:latest
        with:
          entrypoint: /bin/bash
          args: ./ci/unit_test.sh
      - name: py38 integration tests
        if: ${{ matrix.test_type == 'integration' }}
        uses: docker://continuumio/conda-ci-linux-64-python3.8:latest
        with:
          entrypoint: /bin/bash
          args: ./ci/integration_tests.sh
      - name: upload codecov
        run: |
          if [[ $(git diff origin/master --name-only | wc -l) == $(git diff origin/master --name-only | grep docs | wc -l) && $(git diff origin/master --name-only | grep docs) ]]; then
            echo "No codecov report to upload"
          else
            bash <(curl -s https://codecov.io/bash)
          fi

  linux-tests-py39:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test_type: ['unit', 'integration']
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: py39 unit tests
        if: ${{ matrix.test_type == 'unit' }}
        uses: docker://continuumio/conda-ci-linux-64-python3.9:latest
        with:
          entrypoint: /bin/bash
          args: ./ci/unit_test.sh
      - name: py39 integration tests
        if: ${{ matrix.test_type == 'integration' }}
        uses: docker://continuumio/conda-ci-linux-64-python3.9:latest
        with:
          entrypoint: /bin/bash
          args: ./ci/integration_tests.sh
      - name: upload codecov
        run: |
          if [[ $(git diff origin/master --name-only | wc -l) == $(git diff origin/master --name-only | grep docs | wc -l) && $(git diff origin/master --name-only | grep docs) ]]; then
            echo "No codecov report to upload"
          else
            bash <(curl -s https://codecov.io/bash)
          fi
